project_id = "sxenusmscpbbzwrirbos"

[functions.fetch-song]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.provider-health-check]
verify_jwt = false

[functions.fetch-playlist]
verify_jwt = false
